### ISSUE TITLE
Issue with running demo_video.py

### ISSUE THREAD

**Issue by Mudhdhoo** [statho/ScoreHMR#24]
I'm running to this error when I run demo_video.py:

Is there any fix for his? Thanks!

[05/24 20:55:06] INFO     No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'                                                                  acceleratesupport.py:17
apex is not installed
apex is not installed
apex is not installed
load checkpoint from local path: /home/paperspace/ScoreHMR/data/model_weights/vitpose_ckpts/vitpose-h-multi-coco.pth
[2024-05-24 20:55:20,584][pytorch_lightning.utilities.migration.utils][INFO] - Lightning automatically upgraded your loaded checkpoint from v1.8.1 to v2.2.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../.cache/4DHumans/logs/train/multiruns/hmr2/0/checkpoints/epoch=35-step=1000000.ckpt`
WARNING: You are using a SMPL model, with only 10 shape coefficients.
[2024-05-24 20:55:24,962][phalp.trackers.PHALP][INFO] - Loading Predictor model...
[2024-05-24 20:55:25,183][phalp.trackers.PHALP][INFO] - Loading Detection model...
[2024-05-24 20:55:34,404][detectron2.checkpoint.detection_checkpoint][INFO] - [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/ViTDet/COCO/cascade_mask_rcnn_vitdet_h/f328730692/model_final_f05665.pkl ...
[2024-05-24 20:55:37,395][detectron2.checkpoint.detection_checkpoint][INFO] - [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x/139653917/model_final_2d9806.pkl ...
[2024-05-24 20:55:37,582][phalp.trackers.PHALP][INFO] - Setting up Visualizer...
[2024-05-24 20:55:38,021][phalp.trackers.PHALP][INFO] - Setting up DeepSort...
[2024-05-24 20:55:38,021][phalp.trackers.PHALP][INFO] - Saving tracks at : demo_out/videos/phalp_out/breakdancing/results/breakdancing
list index out of range
Traceback (most recent call last):
  File "/home/paperspace/miniconda3/envs/score_hmr/lib/python3.10/site-packages/phalp/trackers/PHALP.py", line 174, in track
    list_of_shots = self.get_list_of_shots(list_of_frames)
  File "/home/paperspace/miniconda3/envs/score_hmr/lib/python3.10/site-packages/phalp/trackers/PHALP.py", line 610, in get_list_of_shots
    if(isinstance(list_of_frames[0], str)):
IndexError: list index out of range

Traceback (most recent call last):
  File "/home/paperspace/ScoreHMR/demo_video.py", line 206, in <module>
    main()
  File "/home/paperspace/ScoreHMR/demo_video.py", line 44, in main
    process_seq(out_root=OUT_DIR, seq=args.input_video, img_dir=img_dir, overwrite=args.overwrite)
  File "/home/paperspace/ScoreHMR/demo/utils.py", line 145, in process_seq
    os.rename(f"{res_dir}/demo_{name}.pkl", res_path)
FileNotFoundError: [Errno 2] No such file or directory: 'demo_out/videos/phalp_out/breakdancing/results/demo_breakdancing.pkl' -> 'demo_out/videos/phalp_out/breakdancing/breakdancing.pkl'

**Comment by statho** [comment]
Please see #9. Probably the frames are not extracted in the right path.
